version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    container_name: sreality_db_container
    environment:
      POSTGRES_PASSWORD: admin1
      POSTGRES_DB: sreality_dat
      POSTGRES_USER: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  
  app:
    build: .
    depends_on:
      db:
        condition: service_started
    ports:
      - "8070:8070"
    links:
      - "db:database"

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - "8081:8080"

volumes:
  db-data:
